/// <reference lib="webworker" />
// Custom SIMP service worker.
// Generated by vite-plugin-pwa using injectManifest strategy so we can
// register push + notificationclick handlers. Workbox precaching and
// runtime caching are injected automatically via `self.__WB_MANIFEST`.
//
// See: https://vite-pwa-org.netlify.app/guide/inject-manifest.html

import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { CacheFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';

declare const self: ServiceWorkerGlobalScope & {
  __WB_MANIFEST: Array<{ url: string; revision?: string | null }>;
};

cleanupOutdatedCaches();
precacheAndRoute(self.__WB_MANIFEST);

// Cache images for 30 days.
registerRoute(
  ({ request }) => request.destination === 'image',
  new CacheFirst({
    cacheName: 'images',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 60,
        maxAgeSeconds: 60 * 60 * 24 * 30,
      }),
    ],
  }),
);

// Push notification received while the SW is active (browser may be
// backgrounded). Show a notification using the payload the backend sent.
self.addEventListener('push', (event: PushEvent) => {
  let payload: { title?: string; body?: string; data?: Record<string, string>; icon?: string; badge?: string } = {};
  try {
    if (event.data) payload = event.data.json();
  } catch {
    payload = { title: 'SIMP', body: event.data?.text() ?? '' };
  }
  const title = payload.title ?? 'SIMP';
  const options: NotificationOptions = {
    body: payload.body ?? '',
    icon: payload.icon ?? '/icons/icon-192.png',
    badge: payload.badge ?? '/icons/icon-192.png',
    data: payload.data ?? {},
    tag: payload.data?.tag ?? 'simp-notification',
  };
  event.waitUntil(self.registration.showNotification(title, options));
});

// User clicked a push notification — focus the existing tab if possible,
// otherwise open the route the backend hinted at in `data.route`.
self.addEventListener('notificationclick', (event: NotificationEvent) => {
  event.notification.close();
  const data = (event.notification.data ?? {}) as { route?: string };
  const target = typeof data.route === 'string' && data.route.startsWith('/') ? data.route : '/';
  event.waitUntil(
    (async () => {
      const allClients = await self.clients.matchAll({ type: 'window', includeUncontrolled: true });
      for (const client of allClients) {
        const url = new URL(client.url);
        if (url.origin === self.location.origin) {
          await client.focus();
          client.postMessage({ type: 'simp:navigate', route: target });
          return;
        }
      }
      await self.clients.openWindow(target);
    })(),
  );
});

self.addEventListener('install', () => {
  self.skipWaiting();
});

self.addEventListener('activate', (event: ExtendableEvent) => {
  event.waitUntil(self.clients.claim());
});

// Periodic Background Sync — let the browser wake the SW on a schedule
// to refresh cached data. Tagged so we can register from the app.
self.addEventListener('periodicsync', (event: ExtendableEvent & { tag?: string }) => {
  if (event.tag === 'simp-refresh') {
    event.waitUntil(
      (async () => {
        try {
          const fresh = await fetch('/api/discovery?refresh=1', { credentials: 'include' });
          const cache = await caches.open('simp-data');
          await cache.put('/api/discovery', fresh.clone());
        } catch {
          // best-effort; no-op on failure
        }
      })(),
    );
  }
});

// Background Sync — replay queued writes when the device comes back online.
self.addEventListener('sync', (event: ExtendableEvent & { tag?: string; waitUntil: (p: Promise<unknown>) => void }) => {
  if (event.tag === 'simp-replay') {
    event.waitUntil(
      (async () => {
        const cache = await caches.open('simp-queue');
        const queued = await cache.keys();
        for (const req of queued) {
          try {
            const body = await cache.match(req);
            if (!body) continue;
            await fetch(req.clone(), { method: req.method, body: await body.text(), credentials: 'include' });
            await cache.delete(req);
          } catch {
            // leave in queue for next attempt
          }
        }
      })(),
    );
  }
});
